
import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "MicroBuild Society McMaster",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body style={{ background: '#fff', minHeight: '100vh', margin: 0 }}>
        <div
          style={{
            minHeight: '100vh',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Image src="/logo.svg" alt="MicroBuild Logo" width={280} height={280} style={{ marginBottom: 40 }} />
          <h2
            style={{
              fontFamily: inter.style.fontFamily,
              fontWeight: 500,
              fontSize: 28,
              color: '#222',
              textAlign: 'center',
              margin: 0,
              letterSpacing: 0.2,
            }}
          >
            In development<br />Check back soon!
          </h2>
        </div>
      </body>
    </html>
  );
}
