import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "MicroBuild Society McMaster",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body style={{ background: '#fff', minHeight: '100vh', margin: 0 }}>
        <Navbar />
        <div
          style={{
            minHeight: '100vh',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
        </div>
      </body>
    </html>
  );
}